# Generated by Django 6.0 on 2025-12-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_article_options_article_published_article_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
